### ISSUE TITLE
Mamyno Project Submission

### ISSUE THREAD

**Issue by mahendrjy** [CodingGarden/seedling-school-01-frontend-project#17]
# Project Name / Title
Mamyno

## Your Name / Title
Mahendra Choudhary

## Project Description
An application where users can search for movies and add to their watch list. After watch the movie they can remove the movie from their watch list.

## Github repo
https://github.com/iampika/mamyno-movie-app

## Project description
https://github.com/iampika/mamyno-movie-app/blob/master/README.md

##  Github Projects
https://github.com/iampika/mamyno-movie-app/projects/1

## How will users interact with your web site?
* [x] Users can search for movies.
* [x] Users can add movies to watch list.
  * [x] Using LocalStorage
* [x] Users can view the watch list.
* [x] Users can delete movies from the watch list.
* [ ] Users can select the status for the movie:
  * Watching
  * Done
* [ ] Users can select a platform where they will watch the movie:
  * Netflix
  * Amazon
  * Hulu
  * Showtime
  * Theater
  * Apple TV
* [ ] Users can add a platform where they want to watch the movie.
* [ ] Users can delete a platform.
* [ ] Users can update a platform.
* [ ] Users can give tags to the movies, so later they can filter through it
  * Anime
  * Comedy
  * Weird
  * Action
  * Horror
  * News
  * Animation
  * Science
  * Drama
  * Sci-Fi
  * Marvel
  * Standup
* [ ] Users can create the tags for the movies.
* [ ] Users can delete the tags for the movies.
* [ ] Users can update the tags for the movies.

## What 3rd Party Web API do you plan to use?
OMDb (The Open Movie Database) API
* Link to the API documentation here - https://www.omdbapi.com/

## Which of the following describes you:

* [x] YouTube Subscriber
* [x] Twitch Follower
* [ ] Patreon Patron
* [ ] Superchat Donor
* [ ] Streamlabs Donor
* [ ] Coding Garden Moderator

**Comment by mahendrjy** [comment]
Submitted this for review! Please let me know if this description will suffice and I will start working. Thanks a ton!

**Comment by w3cj** [comment]
Looks great! I like that you already broke it down into features. Feel free to get started.

**Comment by mahendrjy** [comment]
Thanks a lot.  Here are my wireframes (super basic):

## First Page - Landing Page
![wireframe](https://user-images.githubusercontent.com/31067376/69387895-5de18800-0cef-11ea-880e-4ba685ddfcea.png)

![wireframe2](https://user-images.githubusercontent.com/31067376/69387912-6c2fa400-0cef-11ea-9c48-68afa045d3a4.png)

## Second Page - App Page
![wireframe3](https://user-images.githubusercontent.com/31067376/69393980-c8e88a00-0d02-11ea-8a76-da95082cebd0.png)


![wireframe4](https://user-images.githubusercontent.com/31067376/69393824-57a8d700-0d02-11ea-86dd-437ec406ba22.png)

![wireframe5](https://user-images.githubusercontent.com/31067376/69393835-5f687b80-0d02-11ea-9ec0-18a6bbdc5ada.png)

## Search  Movies
![wireframe6](https://user-images.githubusercontent.com/31067376/69393857-714a1e80-0d02-11ea-93bd-9bc4edec8c67.png)

![wireframe7](https://user-images.githubusercontent.com/31067376/69393880-80c96780-0d02-11ea-88d6-efa728b6862b.png)

## Inspiration
* https://dribbble.com/shots/1682568-Flixus-Homepage-WIP
* https://dribbble.com/shots/3976346-Home-page-of-Tapenet

![inspiration1](https://user-images.githubusercontent.com/31067376/69393904-8de65680-0d02-11ea-8421-f20c1e0e9f44.png)

![inspiration2](https://user-images.githubusercontent.com/31067376/69393915-93dc3780-0d02-11ea-9e80-8e2cf6c9acb2.png)

**Comment by mahendrjy** [comment]
# Questions
1. Can I use sass ?
2. Can I create more pages other than default 2, then I have more freedom to show my creativity?
    * index.html
    * app.html
    * popular-movies.html
    * favourite-movies.html
    * movie.html
3. Can I use an simple animation library https://scrollrevealjs.org/ ?

Thanks a lot.

**Comment by mahendrjy** [comment]
# Landing Page
![Landing Page 1](https://user-images.githubusercontent.com/31067376/69468758-8b910480-0db5-11ea-8e61-19b22fca6bd0.png)

## You can click on the username to see my medium, github and twitter and it's drop down. It's amazing.
![Landing Page 2](https://user-images.githubusercontent.com/31067376/69468796-b8451c00-0db5-11ea-9dcf-a5b1cdc3bbb1.png)

## You can click on colors to change the theme. I know it's amazing.
![Landing Page 3](https://user-images.githubusercontent.com/31067376/69468814-cb57ec00-0db5-11ea-8363-e17cdb717629.png)

![Landing Page 4](https://user-images.githubusercontent.com/31067376/69468817-ce52dc80-0db5-11ea-9174-b0c543be4387.png)

![Landing Page 5](https://user-images.githubusercontent.com/31067376/69468821-d1e66380-0db5-11ea-8759-76bfa9a3bd80.png)

![Landing Page 6](https://user-images.githubusercontent.com/31067376/69468830-d874db00-0db5-11ea-9d0d-e39266cddfcc.png)

![Landing Page 7](https://user-images.githubusercontent.com/31067376/69468832-dc086200-0db5-11ea-89ce-230558a627ad.png)

# Spoiler - My app page
![app](https://user-images.githubusercontent.com/31067376/69468898-3c979f00-0db6-11ea-899c-5a2688c88d77.png)

**Comment by mahendrjy** [comment]
## You can view the landing page live here
https://iampika.github.io/mamyno-movie-app/

**Comment by w3cj** [comment]
> 1. Can I use sass ?

Yes.

> 2. Can I create more pages other than default 2, then I have more freedom to show my creativity?

You can, but it might make it a bit harder for me to review. You might focus on the first application page and then submit when that one is done. After that you can work on more pages.

> 3. Can I use an simple animation library https://scrollrevealjs.org/ ?

Yes.

**Comment by w3cj** [comment]
The wireframes look great and the landing page looks awesome!

**Comment by mahendrjy** [comment]
Thanks a lot.

**Comment by mahendrjy** [comment]
### Stretch Goals Update
I just watched - [Frontend Face-Off - Vanilla JS MVC with CJ Reynolds](https://www.youtube.com/watch?v=ZBilSF7Oi1k)
* [ ] Refactor app to MVC

### Next Challenge
I really want that your next challenge will be on MVC perhaps I don't know much about it (It will be so much fun).

### MVC
I google and search on https://coding.garden/ about MVC and I just watched [Intro to Design Patterns and MVC](https://www.youtube.com/watch?v=BDrUrvqhJ4c)

### Questions
1. In the "Frontend Face-Off" video, you are using classes everywhere. I don't hate classes, I love them, I'm just curios. Can we do this MVC thing with functions and not use classes at all ?

2. Can I think about MVC as how react redux works ? Because I'm thinking Model means store, View means render and Controls means actions.

Thank you so much.

**Comment by w3cj** [comment]
Yeah MVC does not need classes. In that first video, I took an object oriented / class based approach to implement it, but it is not required.

Redux is an implemention of the "flux" pattern. MVC came first so you could say that MVC inspired flux, but flux tries to overcome some flaws of MVC. Both flux and MVC are types of design patterns.

Learn more about "flux" here:
* https://facebook.github.io/flux/
* http://fluxxor.com/what-is-flux.html (fluxxor is another implementation of the flux pattern)

You can see a comparison of MVC and Flux here:
* https://medium.com/hacking-and-gonzo/flux-vs-mvc-design-patterns-57b28c0f71b7

**Comment by mahendrjy** [comment]
Ok. Got it. Thanks a lot for the links.

**Comment by jakepintu** [comment]
## Update
I told you that I will use an animation library https://scrollrevealjs.org/ but today I found an google chrome extension css-brio, with this extension I can enter a class or id of a element or component and then it give so many animations, I didn't count but it have almost 50, and then you can copy the code and use it, it's amazing.

I update the landing page, you can check out - https://jakepintu.github.io/mamyno-movie-app/
* Don't forget to click on themes buttons, it have bugs
* Don't forget to click on the username, it have a drop down animation.

### The way animations are working is:
* I create animations functions such as rubberBandAnimation, fadeInUpAnimation.
* The function add the animation class to the elements and after 1 second (setTimeOut), the function will remove the classes from the animation.
* When the page loads, I call the functions for the initial animation.
* When the user click on change the theme button then it will run the animation function.

### Questions, Problems and Bugs
I know what the bug is but I don't know how to fix it. It's magic.

When you click on change theme buttons, theme will change and the animation will begin, but if you in the middle of animation, you click again on change theme button, then it will not work. Sometime it will or sometime it will not. Click again and again.

I think the reason behind bug is animation have a time of 1 second and if the user click again in that 1s time period, then it will not work. It will first finish the previous animation. 

1. I think in React, we can clear the side effects but how we do this in Vanilla Javascript ?
2. How I unsubscribe or unmount or clear the interval to fix this bug ?
3. By the way, I'm using div as a change theme buttons, so I think I can't disable them, for a time period. Can we disable a div ?

**Comment by mahendrjy** [comment]
## Update
I told you that I will use an animation library https://scrollrevealjs.org/ but today I found an google chrome extension css-brio, with this extension you enter a class or id of an element then you can choose an animation which you like. then you can copy the code and use it, it's amazing. It have so many animations almost 50.

### The way animations will work:
* [x] I will create three functions - toggleAnimation, rubberBandAnimation and fadeInUpAnimation.
* [x] toggleAnimations toggle the class "paused" which is basically animation-play-state.
* [x] When user visit the site, I run rubberBandAnimation and fadeInUpAnimation
* [x] When user click on change themes buttons then the changeTheme function will call toggleAnimation and rubberBandAnimation
* [x] If animation is running and user click again then animation will stop and when user click again the animation will start again.

**Comment by mahendrjy** [comment]
## Udpate - SPA
I'm thinking to do multiple pages with DOM manipulation (SPA) instead of multiple html files. I search about SPA vanilla js, I read couple of articles. I'm excited.

## Question
I read your strech goals, I think I can do all of them but there is one, I have no idea about it. What is it, why it's important and how to do it.
* Use a CI / CD pipeline

I search about it and everywhere people using very weird words such as docker, devOps seems like it is related to testing maybe. I have no idea. Can you please do a live stream just on this topic with examples. I think many other also want to learn about this. Thanks.

## Request
Please add a page on https://coding.garden/, where we can add or vote about on which topic you focus on next live stream. I know I can ask questions during live stream and you read all the messages (I love you) but because of timing, I already missed two live streams for ask questions. 

So after this page, I can ask question and then I can watch live stream anytime.

**Comment by mahendrjy** [comment]
# Project Completed, Deployed, Waiting for Feedback
Hey! I completed my project. Please give me a 📺 LIVE youtube code review, UI/UX review and Readme review. Thanks you so much. Love you.  Please don't go easy on me. I want to improve. Thanks.

# Readme - Table of contents

- [General info](https://github.com/iampika/mamyno-movie-app#What-is-your-motivation-for-creating-this-project)
- [Screenshots](https://github.com/iampika/mamyno-movie-app#Screenshots)
- [Technologies](https://github.com/iampika/mamyno-movie-app#Technologies)
- [Features](https://github.com/iampika/mamyno-movie-app#Features)
- [Setup](https://github.com/iampika/mamyno-movie-app#Setup)
- [Folder Structure](https://github.com/iampika/mamyno-movie-app#Folder-Structure)
- [3rd Party API(s)](https://github.com/iampika/mamyno-movie-app#What-3rd-Party-APIs-will-you-integrate-with)
- [Stretch Goals](https://github.com/iampika/mamyno-movie-app#Will-you-try-to-implement-any-stretch-features)
- [Code Example or I change it to Code Explanation](https://github.com/iampika/mamyno-movie-app#Code-Example)
- [Inspiration](https://github.com/iampika/mamyno-movie-app#Inspiration)

# Live - Github Pages
https://iampika.github.io/mamyno-movie-app/

# Source code
https://github.com/iampika/mamyno-movie-app

**Comment by TWDcarlos** [comment]
Thanks for sharing this 'google chrome extension css-brio'. it also work on Opera

**Comment by iampika** [comment]
Your welcome, I know it's amazing

**Comment by mahendrjy** [comment]
Your welcome, I know it's amazing

**Comment by w3cj** [comment]
### README

* [x] Readme includes instructions for running the project locally

### HTML

* [x] Consistent Indentation
* [x] Includes meta viewport tag for mobile devices  
  * `<meta name="viewport" content="width=device-width, initial-scale=1.0">`
* [x] CSS Links and Font Links are in the head of the document
* [x] JavaScript files are linked at the bottom of the page OR at the top with an onload function OR at the top with a defer attribute
* [ ] Uses semantic tags where available
  * Could use nav, section
* [x] Title / Header links back to home page
* [ ] No extra elements. Only includes the necessary elements to make things work.
  * There are quite a few extra divs. Probably for styling, but the same effect might be possible without that many divs

### JavaScript

* [x] Consistent semicolon usage. Either do or do not. There is no inbetween.
* [x] Consistent quote usage. Either `'` or `"`, don't mix.
* [x] Consistent indentation.
* [ ] Reasonable max line length. Wrap / reformat code when it gets too long.
* [ ] Variable / Function names are clear and concise.
  * [ ] No abbreviations.
* [x] Variable / Function naming convention is consistent. 
  * camelCase or PascalCase or snake_case
* [x] Strings used more than once are in a variable.
  * API_URL etc.
* [x] Functions are as few lines as possible. Code reads like a sentence.
* [x] Function names dictate intent.
* [x] Nested loops avoided where possible.
* [x] Functions take in a reasonable number of parameters. Ideally 3 or less params. Otherwise, use an options object.
* [x] No extra variables.

**Comment by mahendrjy** [comment]
Thanks for the code review. I will soon work on your all advices.
